import os
from flask import Flask, render_template, request, redirect, url_for, session

app = Flask(__name__)
# IMPORTANT: Set a secret key for session management
app.secret_key = 'a_very_secret_key_change_this_in_production'

# --- Configuration ---
# CHANGE THIS TO YOUR IMAGE DIRECTORY!
IMAGE_DIR = 'image_selector_app/static/images/'
# Supported images per page
PAGE_SIZES = [10, 50, 100, 0] # 0 for "All"

# --- Helper Function ---
def get_image_list():
    """Reads all image files from the directory."""
    # Add/modify extensions as needed (case-insensitive)
    valid_extensions = ('.jpg', '.jpeg', '.png', '.gif', '.webp')
    try:
        # Get all filenames, filter by extension, and sort them
        all_images = [
            f for f in sorted(os.listdir(IMAGE_DIR))
            if f.lower().endswith(valid_extensions)
        ]
        return all_images
    except FileNotFoundError:
        print(f"Error: Directory not found at {IMAGE_DIR}")
        return []
    except Exception as e:
        print(f"An error occurred: {e}")
        return []

# --- Routes ---

@app.before_request
def make_session_permanent():
    """Makes the session last until the browser is closed."""
    session.permanent = True

@app.route('/', methods=['GET', 'POST'])
@app.route('/<int:page_num>', methods=['GET', 'POST'])
def index(page_num=1):
    all_images = get_image_list()
    
    # Handle POST request (Selection and Command Generation)
    if request.method == 'POST':
        # Get the list of selected image filenames
        selected_images = request.form.getlist('selected_images')
        command_template = request.form.get('command_template', 'echo {}')

        if not selected_images:
            return render_template('index.html', 
                                    images=[], 
                                    page_num=1, 
                                    total_pages=1, 
                                    page_size=10, 
                                    page_sizes=PAGE_SIZES,
                                    error_message="No images were selected.")
        
        # 1. Generate the shell script content
        script_lines = [
            "#!/bin/bash",
            "# Shell script generated by image_selector_app",
            "# Command template: " + command_template,
            "IMAGE_DIR='" + IMAGE_DIR + "'"
        ]
        
        # 2. Iterate and replace the placeholders
        for image in selected_images:
            # Full path to the image, quoted for safety
            full_path = os.path.join("$IMAGE_DIR", image)
            quoted_full_path = f"'{full_path}'"

            # Filename without extension
            name_only = os.path.splitext(image)[0]
            
            # Replace '{}' with the full path and '{n}' with the name without extension
            command = command_template.replace('{}', quoted_full_path)
            command = command.replace('{n}', name_only)
            
            script_lines.append(command)
            
        final_script = "\n".join(script_lines)
        
        # 3. Store the result in the session to display on a new page
        session['final_script'] = final_script
        session['selected_count'] = len(selected_images)
        
        return redirect(url_for('results'))

    # Handle GET request (Displaying the Image Selector)
    
    # Determine the desired page size
    page_size_str = request.args.get('page_size', str(PAGE_SIZES[0]))
    try:
        page_size = int(page_size_str)
        if page_size not in PAGE_SIZES:
            page_size = PAGE_SIZES[0]
    except ValueError:
        page_size = PAGE_SIZES[0]

    
    # Pagination Logic
    if page_size == 0: # "All" option
        images_to_display = all_images
        total_pages = 1
        page_num = 1
    else:
        total_images = len(all_images)
        total_pages = (total_images + page_size - 1) // page_size
        
        if page_num < 1: page_num = 1
        if page_num > total_pages and total_pages > 0: page_num = total_pages
        
        start_index = (page_num - 1) * page_size
        end_index = start_index + page_size
        images_to_display = all_images[start_index:end_index]

    # Pass data to the template
    return render_template('index.html', 
                           images=images_to_display, 
                           page_num=page_num, 
                           total_pages=total_pages, 
                           page_size=page_size,
                           page_sizes=PAGE_SIZES,
                           total_image_count=len(all_images),
                           # Default template updated to show new placeholder
                           template_command=request.form.get('command_template', 'convert {} -resize 50% {n}_thumb.jpg') 
                           )


@app.route('/results')
def results():
    """Displays the generated shell script."""
    final_script = session.pop('final_script', None)
    selected_count = session.pop('selected_count', 0)
    
    if final_script is None:
        return redirect(url_for('index'))
    
    return render_template('results.html', 
                           final_script=final_script, 
                           selected_count=selected_count)


if __name__ == '__main__':
    # You may need to run this with 'sudo' if your image directory requires elevated permissions
    app.run(debug=True)
